spring.application.name=management_system_for_university
final.date.payment=7
# Adres URL do bazy danych PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:1001/university
# Nazwa u?ytkownika do po??czenia z baz?
spring.datasource.username=root
# Has?o do po??czenia z baz?
spring.datasource.password=123
# Sterownik bazy danych (opcjonalne, je?li nie ustawiono inaczej)
spring.datasource.driver-class-name=org.postgresql.Driver
# W?a?ciwo?ci dla JPA (opcjonalne)
#spring.jpa.hibernate.ddl-auto=update # lub create, validate, none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always

spring.liquibase.change-log=classpath:liquibase-changeLog.xml


